//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CONEXION : DbContext
{
    public CONEXION()
        : base("name=CONEXION")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<C04Clientes> C04Clientes { get; set; }
    public virtual DbSet<C04VENDEDORES> C04VENDEDORES { get; set; }
    public virtual DbSet<CoordenadaSeguimiento> CoordenadaSeguimientoes { get; set; }
    public virtual DbSet<CoordenadasVenta> CoordenadasVentas { get; set; }
    public virtual DbSet<VentanaHoraria> VentanaHorarias { get; set; }
}
