//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class C04Clientes
{
    public string CODIGO { get; set; }
    public string RAZONSOCI { get; set; }
    public string REPRESENTA { get; set; }
    public string DIRECCION { get; set; }
    public string TELEFONOS { get; set; }
    public string NIT { get; set; }
    public string ZONA { get; set; }
    public string VENDEDOR { get; set; }
    public string BARRIO { get; set; }
    public string Limite { get; set; }
    public string Dias { get; set; }
    public Nullable<int> ListaPrecios { get; set; }
    public string Entregador { get; set; }
    public string POP { get; set; }
    public Nullable<int> MARCAS { get; set; }
    public string CANAL { get; set; }
    public string COMPANIA { get; set; }
    public int clienteKey { get; set; }
    public Nullable<double> latitud { get; set; }
    public Nullable<double> longitud { get; set; }
}

public partial class C04VENDEDORES
{
    public int vendedorKey { get; set; }
    public string Codigo { get; set; }
    public string Nombre { get; set; }
    public string Dir { get; set; }
    public string Telefono { get; set; }
    public string Ciudad { get; set; }
    public string Zona { get; set; }
    public string est_vere { get; set; }
    public Nullable<int> Consecutivo { get; set; }
    public Nullable<int> gps { get; set; }
    public string cedula { get; set; }
    public string bodega { get; set; }
    public string usuario { get; set; }
    public string password { get; set; }
}

public partial class CoordenadaSeguimiento
{
    public int seguimientoKey { get; set; }
    public Nullable<double> latitud { get; set; }
    public Nullable<double> longitud { get; set; }
    public Nullable<System.DateTime> fechaMovil { get; set; }
    public Nullable<int> hora { get; set; }
    public Nullable<int> minuto { get; set; }
    public Nullable<int> consecutivoMovil { get; set; }
    public string vendedor { get; set; }
}

public partial class CoordenadasVenta
{
    public int ventasKey { get; set; }
    public Nullable<double> latitud { get; set; }
    public Nullable<double> longitud { get; set; }
    public Nullable<System.DateTime> fechaMovil { get; set; }
    public Nullable<int> hora { get; set; }
    public Nullable<int> minuto { get; set; }
    public string vendedor { get; set; }
    public string cliente { get; set; }
    public Nullable<int> consecutivoMovil { get; set; }
}

public partial class VentanaHoraria
{
    public int ventanaHorariaKey { get; set; }
    public Nullable<System.DateTime> fechaServidor { get; set; }
    public Nullable<System.DateTime> fechaInicio { get; set; }
    public Nullable<System.DateTime> fechaFin { get; set; }
    public Nullable<int> horaInicio { get; set; }
    public Nullable<int> minutoInicio { get; set; }
    public Nullable<int> horaFin { get; set; }
    public Nullable<int> minutoFin { get; set; }
    public string vendedor { get; set; }
}
